language: r
sudo: required
cache: packages
warnings_are_errors: true
r_check_revdep: false
r:
- 3.4.2
- oldrel
- release
- devel

notifications:
  email:
    on_success: never
    on_failure: never

r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()' -t 'aa422d9e-ff83-4262-8e2c-8e45b36817f1'
